package main

import (
	"fmt"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"math/rand"
	"time"
)

func main() {
	// 连接数据库
	dsn := "root:happy123456@tcp(127.0.0.1:3306)/happy?charset=utf8mb4&parseTime=True&loc=Local"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("连接数据库失败: " + err.Error())
	}

	now := time.Now()
	rand.Seed(time.Now().UnixNano())

	// 真实的视频内容
	videos := []map[string]interface{}{
		{
			"tenant_id":     1,
			"type":          "video",
			"title":         "抖音爆款美食教程：3分钟学会网红雪花酥",
			"subtitle":      "超简单零失败，新手也能做",
			"cover_url":     "https://picsum.photos/seed/v1/400/600",
			"content_url":   "https://example.com/video/v1.mp4",
			"description":   "手把手教你制作网红雪花酥，材料简单，步骤详细，保证成功！",
			"author":        "美食博主小厨娘",
			"category":      "美食",
			"view_count":    randInt(50000, 200000),
			"like_count":    randInt(5000, 30000),
			"comment_count": randInt(500, 5000),
			"share_count":   randInt(100, 2000),
			"collect_count": randInt(1000, 10000),
			"duration":      180,
			"status":        1,
			"sort":          100,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "video",
			"title":         "健身达人教你在家练出马甲线",
			"subtitle":      "每天15分钟，30天见效",
			"cover_url":     "https://picsum.photos/seed/v2/400/600",
			"content_url":   "https://example.com/video/v2.mp4",
			"description":   "不需要器械，在家就能练出完美马甲线，跟着我一起动起来！",
			"author":        "健身教练Lisa",
			"category":      "健身",
			"view_count":    randInt(80000, 300000),
			"like_count":    randInt(8000, 50000),
			"comment_count": randInt(1000, 8000),
			"share_count":   randInt(200, 3000),
			"collect_count": randInt(2000, 15000),
			"duration":      900,
			"status":        1,
			"sort":          95,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "video",
			"title":         "旅行Vlog：我在云南的7天",
			"subtitle":      "大理丽江香格里拉完整攻略",
			"cover_url":     "https://picsum.photos/seed/v3/400/600",
			"content_url":   "https://example.com/video/v3.mp4",
			"description":   "记录我在云南的7天旅程，大理古城、洱海、丽江古城、玉龙雪山、香格里拉...",
			"author":        "旅行达人小王",
			"category":      "旅行",
			"view_count":    randInt(100000, 500000),
			"like_count":    randInt(10000, 80000),
			"comment_count": randInt(2000, 10000),
			"share_count":   randInt(500, 5000),
			"collect_count": randInt(5000, 20000),
			"duration":      1200,
			"status":        1,
			"sort":          90,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "video",
			"title":         "化妆教程：日常通勤妆5分钟搞定",
			"subtitle":      "适合上班族的快速妆容",
			"cover_url":     "https://picsum.photos/seed/v4/400/600",
			"content_url":   "https://example.com/video/v4.mp4",
			"description":   "教你5分钟化出精致通勤妆，自然又好看，同事都夸你变美了！",
			"author":        "美妆博主小美",
			"category":      "美妆",
			"view_count":    randInt(60000, 250000),
			"like_count":    randInt(6000, 40000),
			"comment_count": randInt(800, 6000),
			"share_count":   randInt(150, 2500),
			"collect_count": randInt(1500, 12000),
			"duration":      300,
			"status":        1,
			"sort":          85,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "video",
			"title":         "搞笑视频：当程序员遇到Bug",
			"subtitle":      "真实写照，笑着笑着就哭了",
			"cover_url":     "https://picsum.photos/seed/v5/400/600",
			"content_url":   "https://example.com/video/v5.mp4",
			"description":   "程序员日常：改一个Bug出现三个新Bug，真实到让人心疼...",
			"author":        "搞笑达人阿强",
			"category":      "搞笑",
			"view_count":    randInt(200000, 800000),
			"like_count":    randInt(20000, 100000),
			"comment_count": randInt(5000, 20000),
			"share_count":   randInt(1000, 10000),
			"collect_count": randInt(3000, 25000),
			"duration":      60,
			"status":        1,
			"sort":          80,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "video",
			"title":         "萌宠日常：猫咪的一天",
			"subtitle":      "治愈系猫咪视频",
			"cover_url":     "https://picsum.photos/seed/v6/400/600",
			"content_url":   "https://example.com/video/v6.mp4",
			"description":   "记录我家猫咪的一天，睡觉、吃饭、玩耍，太可爱了！",
			"author":        "猫奴小张",
			"category":      "萌宠",
			"view_count":    randInt(150000, 600000),
			"like_count":    randInt(15000, 80000),
			"comment_count": randInt(3000, 15000),
			"share_count":   randInt(800, 8000),
			"collect_count": randInt(4000, 30000),
			"duration":      180,
			"status":        1,
			"sort":          75,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "video",
			"title":         "游戏实况：王者荣耀五杀集锦",
			"subtitle":      "高端局精彩操作",
			"cover_url":     "https://picsum.photos/seed/v7/400/600",
			"content_url":   "https://example.com/video/v7.mp4",
			"description":   "王者荣耀高端局五杀集锦，操作细节满满，学技术必看！",
			"author":        "游戏主播小黑",
			"category":      "游戏",
			"view_count":    randInt(120000, 450000),
			"like_count":    randInt(12000, 60000),
			"comment_count": randInt(2000, 12000),
			"share_count":   randInt(600, 6000),
			"collect_count": randInt(3000, 20000),
			"duration":      600,
			"status":        1,
			"sort":          70,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "video",
			"title":         "音乐翻唱：周杰伦《晴天》",
			"subtitle":      "吉他弹唱版，超治愈",
			"cover_url":     "https://picsum.photos/seed/v8/400/600",
			"content_url":   "https://example.com/video/v8.mp4",
			"description":   "用吉他重新演绎周杰伦经典《晴天》，希望你们喜欢！",
			"author":        "音乐人小林",
			"category":      "音乐",
			"view_count":    randInt(90000, 350000),
			"like_count":    randInt(9000, 50000),
			"comment_count": randInt(1500, 10000),
			"share_count":   randInt(400, 4000),
			"collect_count": randInt(2000, 18000),
			"duration":      270,
			"status":        1,
			"sort":          65,
			"created_at":    now,
			"updated_at":    now,
		},
	}

	// 真实的小说内容
	novels := []map[string]interface{}{
		{
			"tenant_id":     1,
			"type":          "novel",
			"title":         "重生之商业帝国",
			"subtitle":      "重生商战爽文",
			"cover_url":     "https://picsum.photos/seed/n1/400/600",
			"content_url":   "",
			"description":   "重生回到2010年，利用前世记忆打造商业帝国，从一个小程序员到商业巨鳄的传奇故事。",
			"author":        "商战大神",
			"category":      "都市重生",
			"view_count":    randInt(500000, 2000000),
			"like_count":    randInt(50000, 200000),
			"comment_count": randInt(10000, 50000),
			"share_count":   randInt(2000, 20000),
			"collect_count": randInt(50000, 200000),
			"word_count":    2800000,
			"chapter_count": 1200,
			"status":        1,
			"sort":          100,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "novel",
			"title":         "仙武帝尊",
			"subtitle":      "东方玄幻巨作",
			"cover_url":     "https://picsum.photos/seed/n2/400/600",
			"content_url":   "",
			"description":   "少年叶辰偶得仙帝传承，从此踏上修仙之路，逆天改命，成就无上武尊！",
			"author":        "玄幻至尊",
			"category":      "玄幻修仙",
			"view_count":    randInt(800000, 3000000),
			"like_count":    randInt(80000, 300000),
			"comment_count": randInt(15000, 80000),
			"share_count":   randInt(3000, 30000),
			"collect_count": randInt(80000, 300000),
			"word_count":    4500000,
			"chapter_count": 2000,
			"status":        1,
			"sort":          95,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "novel",
			"title":         "甜宠蜜爱：总裁的替身新娘",
			"subtitle":      "豪门甜宠文",
			"cover_url":     "https://picsum.photos/seed/n3/400/600",
			"content_url":   "",
			"description":   "替姐姐出嫁，却意外收获真爱，霸道总裁的独宠甜妻，全程高甜无虐！",
			"author":        "甜文小公主",
			"category":      "现代言情",
			"view_count":    randInt(600000, 2500000),
			"like_count":    randInt(60000, 250000),
			"comment_count": randInt(12000, 60000),
			"share_count":   randInt(2500, 25000),
			"collect_count": randInt(60000, 250000),
			"word_count":    1200000,
			"chapter_count": 600,
			"status":        1,
			"sort":          90,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "novel",
			"title":         "诡秘之主",
			"subtitle":      "克苏鲁风格奇幻巨作",
			"cover_url":     "https://picsum.photos/seed/n4/400/600",
			"content_url":   "",
			"description":   "蒸汽与机械的浪潮中，谁能触及真正的神？克苏鲁风格奇幻小说巅峰之作！",
			"author":        "爱潜水的乌贼",
			"category":      "奇幻悬疑",
			"view_count":    randInt(1000000, 5000000),
			"like_count":    randInt(100000, 500000),
			"comment_count": randInt(20000, 100000),
			"share_count":   randInt(5000, 50000),
			"collect_count": randInt(100000, 500000),
			"word_count":    3500000,
			"chapter_count": 1432,
			"status":        1,
			"sort":          85,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "novel",
			"title":         "斗破苍穹",
			"subtitle":      "玄幻经典之作",
			"cover_url":     "https://picsum.photos/seed/n5/400/600",
			"content_url":   "",
			"description":   "三十年河东，三十年河西，莫欺少年穷！萧炎的逆袭之路，热血玄幻经典！",
			"author":        "天蚕土豆",
			"category":      "玄幻热血",
			"view_count":    randInt(2000000, 8000000),
			"like_count":    randInt(200000, 800000),
			"comment_count": randInt(40000, 200000),
			"share_count":   randInt(10000, 100000),
			"collect_count": randInt(200000, 800000),
			"word_count":    5300000,
			"chapter_count": 1648,
			"status":        1,
			"sort":          80,
			"created_at":    now,
			"updated_at":    now,
		},
	}

	// 真实的图文内容
	imageTexts := []map[string]interface{}{
		{
			"tenant_id":     1,
			"type":          "image_text",
			"title":         "日本旅游必去的10个小众景点",
			"subtitle":      "避开人潮，发现不一样的日本",
			"cover_url":     "https://picsum.photos/seed/it1/400/600",
			"content_url":   "",
			"description":   "除了东京大阪，日本还有这些绝美小众景点，人少景美，值得一去！",
			"author":        "旅行摄影师阿杰",
			"category":      "旅行",
			"view_count":    randInt(30000, 150000),
			"like_count":    randInt(3000, 20000),
			"comment_count": randInt(500, 3000),
			"share_count":   randInt(100, 1000),
			"collect_count": randInt(2000, 15000),
			"word_count":    2500,
			"status":        1,
			"sort":          100,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "image_text",
			"title":         "2024年最流行的10种装修风格",
			"subtitle":      "装修必看，总有一款适合你",
			"cover_url":     "https://picsum.photos/seed/it2/400/600",
			"content_url":   "",
			"description":   "从北欧风到新中式，2024年最流行的装修风格大盘点，附详细案例图！",
			"author":        "室内设计师小王",
			"category":      "家居",
			"view_count":    randInt(40000, 180000),
			"like_count":    randInt(4000, 25000),
			"comment_count": randInt(600, 4000),
			"share_count":   randInt(150, 1500),
			"collect_count": randInt(3000, 20000),
			"word_count":    3200,
			"status":        1,
			"sort":          95,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "image_text",
			"title":         "减肥必看：低卡美食食谱大全",
			"subtitle":      "好吃不胖，健康减肥",
			"cover_url":     "https://picsum.photos/seed/it3/400/600",
			"content_url":   "",
			"description":   "50道低卡美食食谱，让你在享受美食的同时轻松瘦身，告别节食痛苦！",
			"author":        "营养师小李",
			"category":      "美食健康",
			"view_count":    randInt(50000, 200000),
			"like_count":    randInt(5000, 30000),
			"comment_count": randInt(800, 5000),
			"share_count":   randInt(200, 2000),
			"collect_count": randInt(4000, 25000),
			"word_count":    4500,
			"status":        1,
			"sort":          90,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "image_text",
			"title":         "职场穿搭指南：如何穿出专业感",
			"subtitle":      "提升职场形象的穿搭技巧",
			"cover_url":     "https://picsum.photos/seed/it4/400/600",
			"content_url":   "",
			"description":   "职场穿搭全攻略，从面试到日常办公，教你如何穿出专业感和高级感！",
			"author":        "时尚博主小美",
			"category":      "时尚",
			"view_count":    randInt(35000, 160000),
			"like_count":    randInt(3500, 22000),
			"comment_count": randInt(550, 3500),
			"share_count":   randInt(120, 1200),
			"collect_count": randInt(2500, 18000),
			"word_count":    2800,
			"status":        1,
			"sort":          85,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "image_text",
			"title":         "摄影技巧：手机也能拍出大片",
			"subtitle":      "手机摄影完全指南",
			"cover_url":     "https://picsum.photos/seed/it5/400/600",
			"content_url":   "",
			"description":   "不需要单反，手机也能拍出专业级照片！构图、光线、后期全攻略！",
			"author":        "摄影师老张",
			"category":      "摄影",
			"view_count":    randInt(45000, 190000),
			"like_count":    randInt(4500, 28000),
			"comment_count": randInt(700, 4500),
			"share_count":   randInt(180, 1800),
			"collect_count": randInt(3500, 22000),
			"word_count":    3800,
			"status":        1,
			"sort":          80,
			"created_at":    now,
			"updated_at":    now,
		},
	}

	// 真实的短剧内容
	shortDramas := []map[string]interface{}{
		{
			"tenant_id":     1,
			"type":          "short_drama",
			"title":         "霸道总裁爱上我",
			"subtitle":      "甜宠短剧",
			"cover_url":     "https://picsum.photos/seed/sd1/400/600",
			"content_url":   "https://example.com/drama/sd1.mp4",
			"description":   "平凡女孩意外成为霸道总裁的贴身秘书，从此开启甜蜜恋爱之旅...",
			"author":        "甜宠剧场",
			"category":      "都市甜宠",
			"view_count":    randInt(300000, 1000000),
			"like_count":    randInt(30000, 100000),
			"comment_count": randInt(5000, 30000),
			"share_count":   randInt(1000, 10000),
			"collect_count": randInt(20000, 80000),
			"duration":      120,
			"status":        1,
			"sort":          100,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "short_drama",
			"title":         "重生之复仇女王",
			"subtitle":      "爽文短剧",
			"cover_url":     "https://picsum.photos/seed/sd2/400/600",
			"content_url":   "https://example.com/drama/sd2.mp4",
			"description":   "重生归来，她要让曾经伤害过她的人付出代价，复仇爽剧！",
			"author":        "爽剧工厂",
			"category":      "都市复仇",
			"view_count":    randInt(400000, 1500000),
			"like_count":    randInt(40000, 150000),
			"comment_count": randInt(8000, 40000),
			"share_count":   randInt(2000, 15000),
			"collect_count": randInt(30000, 100000),
			"duration":      150,
			"status":        1,
			"sort":          95,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "short_drama",
			"title":         "穿越之古代奇缘",
			"subtitle":      "古装穿越短剧",
			"cover_url":     "https://picsum.photos/seed/sd3/400/600",
			"content_url":   "https://example.com/drama/sd3.mp4",
			"description":   "现代女孩意外穿越到古代，与王爷展开一段跨越时空的爱恋...",
			"author":        "古装剧场",
			"category":      "古装穿越",
			"view_count":    randInt(350000, 1200000),
			"like_count":    randInt(35000, 120000),
			"comment_count": randInt(6000, 35000),
			"share_count":   randInt(1500, 12000),
			"collect_count": randInt(25000, 90000),
			"duration":      180,
			"status":        1,
			"sort":          90,
			"created_at":    now,
			"updated_at":    now,
		},
	}

	// 真实的漫剧内容
	comics := []map[string]interface{}{
		{
			"tenant_id":     1,
			"type":          "comic",
			"title":         "斗罗大陆",
			"subtitle":      "热血玄幻漫剧",
			"cover_url":     "https://picsum.photos/seed/c1/400/600",
			"content_url":   "",
			"description":   "唐三觉醒双生武魂，踏上成神之路，热血玄幻漫剧巅峰之作！",
			"author":        "唐家三少",
			"category":      "玄幻热血",
			"view_count":    randInt(1000000, 5000000),
			"like_count":    randInt(100000, 500000),
			"comment_count": randInt(20000, 100000),
			"share_count":   randInt(5000, 50000),
			"collect_count": randInt(100000, 500000),
			"chapter_count": 500,
			"status":        1,
			"sort":          100,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "comic",
			"title":         "一人之下",
			"subtitle":      "国漫经典之作",
			"cover_url":     "https://picsum.photos/seed/c2/400/600",
			"content_url":   "",
			"description":   "张楚岚的异人之旅，揭开隐藏世界的秘密，国漫巅峰之作！",
			"author":        "米二",
			"category":      "都市异能",
			"view_count":    randInt(800000, 4000000),
			"like_count":    randInt(80000, 400000),
			"comment_count": randInt(15000, 80000),
			"share_count":   randInt(4000, 40000),
			"collect_count": randInt(80000, 400000),
			"chapter_count": 600,
			"status":        1,
			"sort":          95,
			"created_at":    now,
			"updated_at":    now,
		},
		{
			"tenant_id":     1,
			"type":          "comic",
			"title":         "狐妖小红娘",
			"subtitle":      "唯美爱情漫剧",
			"cover_url":     "https://picsum.photos/seed/c3/400/600",
			"content_url":   "",
			"description":   "人与妖的爱情故事，跨越千年的羁绊，唯美动人的爱情漫剧！",
			"author":        "小新",
			"category":      "爱情玄幻",
			"view_count":    randInt(900000, 4500000),
			"like_count":    randInt(90000, 450000),
			"comment_count": randInt(18000, 90000),
			"share_count":   randInt(4500, 45000),
			"collect_count": randInt(90000, 450000),
			"chapter_count": 550,
			"status":        1,
			"sort":          90,
			"created_at":    now,
			"updated_at":    now,
		},
	}

	// 插入所有数据
	allMaterials := [][]map[string]interface{}{videos, novels, imageTexts, shortDramas, comics}
	count := 0

	for _, materials := range allMaterials {
		for _, material := range materials {
			result := db.Table("material").Create(&material)
			if result.Error != nil {
				fmt.Printf("插入失败: %v\n", result.Error)
			} else {
				count++
			}
		}
	}

	fmt.Printf("\n✅ 成功插入 %d 条真实物料数据\n", count)
	fmt.Println("数据类型:")
	fmt.Printf("  - 视频: %d 条\n", len(videos))
	fmt.Printf("  - 小说: %d 条\n", len(novels))
	fmt.Printf("  - 图文: %d 条\n", len(imageTexts))
	fmt.Printf("  - 短剧: %d 条\n", len(shortDramas))
	fmt.Printf("  - 漫剧: %d 条\n", len(comics))
}

func randInt(min, max int) int {
	return rand.Intn(max-min) + min
}
